
project_id = "iljrrqtcmctrydrtnttg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[[db.migrations]]
path = "migrations"

[functions.send-order-confirmation]
verify_jwt = false
